### ISSUE TITLE
Update to latest tendermint release

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/bcp-demo#18]
0.19 has some breaking changes on how the validator keys are stored (and how everything is encoded actually). We need to upgrade to 0.19+ before working on PoA.

With the way 0.19 was released, I don't have much faith in it's stability, and would prefer to wait for tendermint to have a successful testnet deploy on top of it, or the next release (0.19.1 or 0.20) which should fix some bugs.

**Comment by ethanfrey** [comment]
Notes... 0.19.5 is open, 0.19.6 is almost there

We need to update the Makefile and Docker images to deploy it, but we will need to make some changes to our code to be compatible. We do not include tendermint in our code, but need the same version of abci package, which is the interface.

* Update abci dep in weave to match that in tendermint 0.19.x
* Fix any issues that break
* Make sure that InitChain uses the AppState variable passed in over ABCI and not filesystem.
* Check CHANGELOG to see if there is more to do

**Comment by ethanfrey** [comment]
https://github.com/confio/weave/blob/master/app/store.go#L289-L318 at least

**Comment by ethanfrey** [comment]
Okay, it seems 0.19.6 and 0.19.7 are out and have some reliability fixes that may solve some of the issues we had when chaos-monkey-testing the first testnet.

**Comment by ruseinov** [comment]
Yep, looking into it.

**Comment by ruseinov** [comment]
```Changes to tm, breaking:
* [rpc/client] TxSearch and UnconfirmedTxs have new arguments (see below)
* [rpc/client] TxSearch returns ResultTxSearch
* [cmd] show_node_id now returns an error if there is no node key
* [rpc]: changed the output format for the /status endpoint (see 
Upgrade from go-wire to go-amino. This is a sweeping change that breaks everything that is serialized to disk or over the network.
See github.com/tendermint/go-amino for details on the new format.
See scripts/wire2amino.go for a tool to upgrade genesis/priv_validator/node_key JSON files.
* [rpc] Listening address must contain tcp:// or unix:// prefix
```

**Comment by ruseinov** [comment]
basically need to take into account most of these

**Comment by ethanfrey** [comment]
Good points.

Yeah, the rpc client code will break weave-js.  Actually in a number of places I believe (they get sloppy between hex and base64 which they don't mention there). I will take care of that.

Breaking cli and file changes will need to reflect in scripts.

Don't worry about upgrading any existing kets (wire2amino), we can still wipe out all history and make a clean start.

If you get stuck with anything more tied to the core codebase and not devops (like updating the dep jungle of tendermint from weave), please let me know. I've fought a lot with this in the past and can probably help you there.

**Comment by ruseinov** [comment]
@ethanfrey will do, should be fine though I hope as I've doing go stuff for quite some time tho. Hopefully will be able to manage

**Comment by ethanfrey** [comment]
I know, just saying, lots of go devs have struggled with the tendermint dep jungle....

The internal team had plenty of trouble updating vendor between their own repos as well... only the old timers would have their tricks (but this was all with glide, maybe easier with dep).

**Comment by ruseinov** [comment]
@ethanfrey I think this could be closed now, right?

**Comment by ethanfrey** [comment]
yup.
