### ISSUE TITLE
Add state channel

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/bcp-demo#22]
(Note: this may belong in another repo... let's discuss that element before coding)

State channels are nice for bundling many small off-chain payments into one payment.

They basically work as an escrow (Key A will send X tokens to Key B). However, there is no arbiter to release it, but rather signed messages. 

We must specify a message format in protobuf or json, which is distinct from any Transaction format we have. This must contain the channel and how much to release, something like:

 ```
{
  "channel_id": "1234", 
  "payment": {
      "whole": 17,
      "fractional": 12345
  }
}
```

Maybe we can add timestamps, sequence numbers, etc. In any case we need to add a signature.

The recipient can post a message to the channel to release funds. If the message is properly signed by the sender of the channel, we check how much has been previously release. If the new message is a higher amount, we release the difference and update the amount claimed.

At some timeout, the sender can return all unspent tokens to their account.

Example usage:

I can bond eg. 100 tokens for your service (on demand VMs). As I use some hours, I can send you off-chain messages, each with a higher amount (0.01, 0.02, 0.03...). At any point you can claim the tokens I have promised up to this point, by passing the highest-value message to the chain. A week later you can claim some more tokens.

This allows us to have small denominated payments without overloading the blockchain, and both the seller and the buyer of the service can reduce exposure to any bills being unpaid or paid services not delivered.

**Comment by husio** [comment]
I am closing this. It is being implemented in https://github.com/iov-one/weave with related issues created in the same repository.
