### ISSUE TITLE
Testnet deployment script

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/bcp-demo#7]
Deploy tendermint + bcp-demo with 4 nodes

Script should be easy to run by any dev to deploy to on a cloud provider.
Preference: ansible or terraform, but not hard requirements.

See:

- https://tendermint.readthedocs.io/en/master/deploy-testnets.html
- https://github.com/tendermint/alpha

**Comment by ruseinov** [comment]
@ethanfrey To be honest I was inclined to deploy this stuff as docker containers to kubernetes, for example.

This way we could have this working on both local and remote and won't need to deal with ansible and terraform, as this is painful, especially when stuff gets bigger.

**Comment by alpe** [comment]
I am a big fan of Kubernetes and see the benefits in my every day my work. A kubernetes cluster would become quite handy for our monitoring and other infrastructure as well as Prometheus for example integrates super nicely and scrapes based on annotations already. Same for inbound ingress traffic routing. But unless we go for a product like GKE or others there will be some setup costs for the environment. An official Testnet should mirror production net. 

There are tools like docker-notary (and grafeas) we can used to add signatures to the artifacts and solve the "trust the origin problem" and prevent running manipulated artifacts.

With containers we should aim for a single process as tendermint did in their example IMHO. That's much easier to build, run and monitor then multiple processes. My personal goal is aways to use minimal containers where possible. With Go and static compilation we could build on top of the `scratch` image, which leaves less attack vectors 🚀 

Docker artifacts and kubernetes yaml files would definitively reduce the time to run a validator node but as @ethanfrey pointed out already, not everybody may like docker containers. So we would need to provide binaries anyway to meet them where they are. A common practice is to push binaries to github release and docker containers to docker-hub (and docker-notary).
What I have learned from stellar.org is that when you don't provide official containers some other people will build them. We wouldn't be in control what they contain and keep them up to date with our product versions.

**Comment by ruseinov** [comment]
Yeah, I've been building quite a bit of go images myself too, I like them minimal.
Scratch will do just fine, gonna have create a dockerhub repo @ethanfrey and sort out the access.

For sure we have to be running 1 process per container, as this makes the setup very straightforward: just execute the binary and collect them logs.

I'm going to sort out the Dockerfiles first then. @alpe thanks for pointing out docker-notary as I have never used it before, didn't have the need - I will look into that as well.

**Comment by ruseinov** [comment]
Tendermint actually has example dockerfile already, but they don't use anything like grafeas to validate the images.

@ethanfrey @alpe So what's our plan here? Do we introduce binaries for both bcp-demo and tendermint then?

**Comment by ruseinov** [comment]
@alpe as a first step my plan was to introduce a script to bcp-demo that would:
1. Build statically-linked linux binary 
2. Package that into a scratch container and use grafeas/docker-notary to bulletproof it
3. Via CircleCI run these scripts and deploy both the binary and the container to their appropriate places (github and dockerhub)

I guess we can live with official tendermint binaries/docker containers for now and focus only on bcp-demo. 

I'm still looking into all of the ins and outs of bcp-demo, my plan is to make this work via 2 docker containers (tendermint + bcp-demo) on local first.

**Comment by alpe** [comment]
1. 👍 
2. 👍 but don't spend too much time on grafeas/ notary now. IMHO, we can add that in any of the next iterations when we already have a running cluster.
3. This depends a bit how we want to release. Not ever push/ merge to master is necessarily a release or release candidate. Also circleCI should not be considered as trusted build environment (in terms of security) as we don't own it. Let's talk about this in a call.

Can we also talk about 1 container vs 2? when we go with 2 we should fork the repo and build our own containers with signatures. Otherwise we can not really trust the process how they were build. But that can be a future iteration as well.

**Comment by ethanfrey** [comment]
Just catching up on github issues... I think we discussed this in the call, but adding notes here:

1. We want docker images for tendermint and for bov, two containers.
2. We need a way to build a genesis file for multiple validator nodes. There are a few approaches that can be automated, but all involved a central coordinator. That is fine for now, and Roman can just take the path that is easiest to start with.
3. We need docker images for bov and tendermint. They can be pushed to dockerhub - one1
4. We want to have two 4-7 node internal devnets working by June 1. These are not even testnets, and we should aim to rip them down and rebuild with the best tools available in ~2 week sprint cycles. To keep iterating on the process.

**Comment by ethanfrey** [comment]
@alpe got a one node kubernetes deploy working with ssl certificates and is working on integrating some monitoring tools, like grafana and prometheus. This is more related to https://github.com/confio/weave/issues/17 but these two pieces kind of go hand-in-hand, so I mention it here.

**Comment by ruseinov** [comment]
Containerised BOV here: https://github.com/iov-one/bcp-demo/pull/19#pullrequestreview-122575652

**Comment by ruseinov** [comment]
Working on tendermint image for multi-node deployment.

**Comment by ruseinov** [comment]
The deployment now works, we have a couple of things left to be done:

1. document nuances of multi-node tendermint deployment in ops repo
2. Possibly create a tendermint issue about node_id stuff, not sure though if that needs to be done, gotta check latest tendermint docs @ethanfrey first.

**Comment by ethanfrey** [comment]
Tested deployed testnet along with bcp-proxy cli and it all worked flawlessly.
Great job!

**Comment by ruseinov** [comment]
This might be considered complete as soon as this PR https://github.com/iov-one/ops/pull/1 is closed.

But, this is up to @ethanfrey to decide.

**Comment by ethanfrey** [comment]
Yup. Well done.
I merged in the pr in ops.
